### ISSUE TITLE
Frontal només en català

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/translateib#16]
Així com marca l'article 13.3 el Decret 49/2018, sobre l'ús de les llengües oficials en l'Administració de la Comunitat Autònoma de les Illes Balears, es sol·licita que el frontal només sigui en català. Es proposa, per això, ocultar el botó de "Castellano".

![image](https://github.com/user-attachments/assets/0907f269-db9c-4836-b3d9-eb34d63426f3)

**Comment by slromero-indra** [comment]
Hemos subido varios cambios, cuando podáis lo validáis.
