### ISSUE TITLE
Canviar context per adaptar-lo als estàndards

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/translateib#18]
Es demana canviar el mòdul "<context>/translatorib/api/" per "<context>/translatoribapi/interna" per seguir el que marquen els estàndards de CAIB.

D'aquesta manera, així com es va proposar a la anàlisi inicial, a l'hora de desenvolupar el mòdul d'estadístiques per a la reutilització de dades, ja el podrem posar davall el context "/translatorib/externa/"

![image](https://github.com/user-attachments/assets/ba7fe74c-be6a-4e2d-bdd3-6b1a87a78513)

**Comment by slromero-indra** [comment]
Hemos subido varios cambios, cuando podáis lo validáis.
